version: '3.3'

services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      NODE_ENV: development
    ports:
      - '3001:3001'
    restart: always

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_DB: 'ecommerce'
      POSTGRES_USER: 'parshant'
      POSTGRES_PASSWORD: 'dhall010'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    ports:
      - '5432-5432'


  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  pgdata:
  pgadmin-data:



